In [2]:
import numpy as np

In [3]:
np.__version__

'1.20.3'

<h1>Criando Matrizes</h1>

In [42]:
# Inicializando como tipo array

array = np.array([[1, 2, 3],[4, 5, 6]])
ones_array = np.ones((2, 3))
forced_type_array = np.array([1, 2], dtype=np.float64)

[[1 2 3]
 [4 5 6]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[1. 2.] 

int32
float64
float64


In [50]:
print("ARRAY SIMPLES, ROW/COLUMN -", 
      array.shape, "\n", array, "\n")

print("ARRAY TIPO ONES, ROW/COLUMN -", 
      ones_array.shape, "\n", ones_array, "\n")

print("ARRAY SIMPLES FORTEMENTE TIPADO, ROW/COLUMN -", 
      forced_type_array.shape, "\n", forced_type_array, "\n")

# dtype - DATA TYPE
print("---TIPO DE CADA DADO---")
print("array: ", array.dtype)
print("ones_array: ", ones_array.dtype)
print("forced_type_array: ", forced_type_array.dtype)

ARRAY SIMPLES, ROW/COLUMN - (2, 3) 
 [[1 2 3]
 [4 5 6]] 

ARRAY TIPO ONES, ROW/COLUMN - (2, 3) 
 [[1. 1. 1.]
 [1. 1. 1.]] 

ARRAY SIMPLES FORTEMENTE TIPADO, ROW/COLUMN - (2,) 
 [1. 2.] 

---TIPO DE CADA DADO---
array:  int32
ones_array:  float64
forced_type_array:  float64


In [37]:
# Convertendo array em matriz

matrix = np.matrix(array)

print("Tipo: ", type(matrix))
print("Dimensao: ", np.shape(matrix))
print("Tamanho: ", matrix.size)
print("Tamanho na memoria: ", matrix.nbytes, "bytes")

Tipo:  <class 'numpy.matrix'>
Dimensao:  (2, 3)
Tamanho:  6
Tamanho na memoria:  24 bytes
