In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

<h1>Criando Arrays</h1>

In [38]:
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
auto_vector = np.arange(0, 100, 5)
zeros_vector = np.zeros(10)
eye_array = np.eye(3)
li_space_array = np.linspace(0, 10)

In [39]:
print("VETOR\n", vector, "\n")
print("VETOR AUTOMATICO\n", auto_vector, "\n")
print("ZEROS VETOR\n", zeros_vector, "\n")
print("EYE ARRAY\n", eye_array, "\n")
print("LIN SPACE ARRAY\n", li_space_array, "\n")


VETOR
 [ 0  1  2  3  4  5  6  7  8  9 10] 

VETOR AUTOMATICO
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95] 

ZEROS VETOR
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

EYE ARRAY
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

LIN SPACE ARRAY
 [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ] 

