In [47]:
import numpy as np

In [48]:
first_array = np.diag(np.arange(3))
first_array

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [49]:
second_array = np.arange(10)
second_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# retornando os valores dos indices fatiados
second_array[2:9:3] 

array([2, 5, 8])

In [51]:
# comparacao
np.array_equal(first_array ,second_array)


False

In [52]:
# Metodo around == arredondar .5 sempre joga para cima
float_array = ([1.2, 2.3, 3.0, 4.2, 5., 6.1, 7.5, 8.8])
print(float_array)

around_array = np.around(float_array)
print(around_array)

[1.2, 2.3, 3.0, 4.2, 5.0, 6.1, 7.5, 8.8]
[1. 2. 3. 4. 5. 6. 8. 9.]


In [53]:
# copiando elementos de array para vetor
copy_array = first_array.flatten()

print(copy_array)

[0 0 0 0 1 0 0 0 2]


In [55]:
# concatenando arrays

np.concatenate(([1, 2 , 3], [10, 20, 30]), axis = 0)

array([ 1,  2,  3, 10, 20, 30])