In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

<h1>Criando Arrays</h1>

In [24]:
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
auto_vector = np.arange(0, 100, 5)
zeros_vector = np.zeros(10)
eye_array = np.eye(3)
li_space_array = np.linspace(0, 10)

In [37]:
print("VETOR\n", vector, "\n")
print("VETOR AUTOMATICO\n", auto_vector, "\n")
print("ZEROS VETOR\n", zeros_vector, "\n")
print("EYE MATRIZ\n", eye_array, "\n")
print("LIN MATRIZ\n", li_space_array, "\n")


VETOR
 [ 0  1  2  3  4  5  6  7  8  9 10] 

VETOR AUTOMATICO
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95] 

ZEROS VETOR
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

EYE MATRIZ
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

